image: rust

stages:
  - test
  - deploy

test:
  tags:
    - "lightweight"
  stage: test
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --color=always --check
    - cargo test --all-features -- --color=always
    - cargo clippy

pages:
  tags:
    - "lightweight"
  stage: deploy
  script:
    - cargo doc --all-features
    - mv target/doc public
  artifacts:
    paths:
      - 'public'